version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "vendor/main:"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
    - module/main
    - ci/dependabot
    - enhancement
  - package-ecosystem: gomod
    directory: /cmd
    schedule:
      interval: daily
    commit-message:
      prefix: "vendor/cmd:"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
        # updated manually due to replace directives
      - dependency-name: "github.com/cilium/cilium"
        # updated manually when releasing
      - dependency-name: "github.com/cilium/fake"
    labels:
    - module/cmd
    - ci/dependabot
    - enhancement
  - package-ecosystem: gomod
    directory: /flow
    schedule:
      interval: daily
    commit-message:
      prefix: "vendor/flow:"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
        # updated manually due to replace directives
      - dependency-name: "github.com/cilium/cilium"
        # updated manually when releasing
      - dependency-name: "github.com/cilium/fake"
    labels:
    - module/flow
    - ci/dependabot
    - enhancement
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    labels:
    - ci/dependabot
    - enhancement
