# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    goheader:
      template: |-
        SPDX-License-Identifier: Apache-2.0
        Copyright Authors of Cilium
    gosec:
      excludes:
        - G104 # Audit errors not checked
        - G307 # Deferring a method which returns an error
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    rules:
      - linters: [errcheck]
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv).
      - linters: [err113]
        text: "do not define dynamic errors, use wrapped static errors instead"

      - linters: [gosec]
        text: "G404" # Use of weak random number generator (math/rand instead of crypto/rand)
      # TODO: remove the staticcheck exceptions below once we have switched to
      # using crypto/rand instead of math/rand
      - linters: [staticcheck]
        text: "SA1019: rand.Read has been deprecated since Go 1.20 because it shouldn't be used"
      - linters: [staticcheck]
        text: "SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0"
issues:
  # Set to 0 to disable (default is 3)
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
