GO ?= go
TEST_TIMEOUT ?= 5s
GO_BUILD_FLAGS ?=
GO_TEST_FLAGS ?= -timeout=$(TEST_TIMEOUT) -race -cover
GO_BENCH_FLAGS ?= -timeout=$(TEST_TIMEOUT) -bench=.
INSTALL = $(QUIET)install
BINDIR ?= /usr/local/bin
TARGET := fake

# renovate: datasource=github-releases depName=golangci/golangci-lint
GOLANGCILINT_WANT_VERSION = 2.8.0
GOLANGCILINT_VERSION = $(shell golangci-lint version --short 2>/dev/null)
