GO ?= go
TEST_TIMEOUT ?= 5s
GO_BUILD_FLAGS ?=
GO_TEST_FLAGS ?= -timeout=$(TEST_TIMEOUT) -race -cover
GO_BENCH_FLAGS ?= -timeout=$(TEST_TIMEOUT) -bench=.
INSTALL = $(QUIET)install
BINDIR ?= /usr/local/bin
TARGET := fake

GOLANGCILINT_WANT_VERSION = 2.0.1
GOLANGCILINT_VERSION = $(shell golangci-lint version --short 2>/dev/null)
